MoneyShop:
  COBBLESTONE: 1
  DIRT: 1
  SAND: 1
  SANDSTONE: 1
  CUT_SANDSTONE: 1
  CHISELED_SANDSTONE: 1
  RED_SANDSTONE: 1
  GRAVEL: 1
  GRANITE: 1
  DIORITE: 1
  ANDESITE: 1
  DARK_OAK_LOG: 1
  JUNGLE_LOG: 1
  ACACIA_LOG: 1
  BIRCH_LOG: 1
  SPRUCE_LOG: 1
  OAK_LOG: 1
  COAL: 50
  IRON_INGOT: 100
  REDSTONE: 1000
  LAPIS_LAZULI: 1000
  GOLD_INGOT: 2000
  DIAMOND: 10000